version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:password
      - POSTGRES_DATABASE:speech_recognition
    volumes:
      - /Users/a123/go/docker-volumes/postgres:/var/lib/postgresql/data
